In [1]:
import torch

In [2]:
a  = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.int32)

In [3]:
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [4]:
#ten evenly distributed values between 1 and -1
b = torch.linspace(-1, 1, 10)

In [5]:
print(b)

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])


Bad pipe message: %s [b"@\xb4(z\x94\xb2\xd6\xe1,\xc6D&b\xad\x00\x16p\x08 \xafU\xa6\xdbE\xf5%\x8c\xf9\xa1\xb4ly\\\xbb\x91f\xf6gj\xcc'G\xd3\xaa\xee_@$\xd7\x17_\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00"]
Bad pipe message: %s [b'\x1d\x00\x17\x00\x1e\x00\x19\x00\x18']
Bad pipe message: %s [b'\xed9\xbeC\xd1\xd2J\x0e \x1e\xe2zgH\x94\x985\xf5\x00\x00\xa2\xc0\x14\xc0', b'9\x008\x007\x006\x00\x88']
Bad pipe message: %s [b'\xf6\xec\xbd\xa4y\xe2\x00\x85\x8b\xb7|K\xa7\x83\xda\xd5\x1f\xe7\x00\x00>\xc0\x14\xc0\n\x009\x008\x007\x006\xc0\x0f\xc0\x05\x005\xc0\x13\xc0\t\x003\x002\x001\x000\xc0\x0e\xc0\x04\x00/\x00\x9a\x00\x99\x00\x98\x00\x97\x00\x96\x00\x07\xc0\x11\xc0\x07\xc0\x0c\xc0\x02\x00\x05\x00\x04\x00\xff\x02\x01\x00\x00C\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04', b'\x01\x02']
Bad pipe message: %s [b'\xa4\xf5u\xb01\x8d\xfd\xc8\x02\xf0\xa5*j;\xd6]\xcc\xb7\x00\x00\xa2\xc0\x14

In [7]:
#random number generator
c = torch.rand(3, 4)

In [8]:
print(c)

tensor([[0.7410, 0.5783, 0.1123, 0.3175],
        [0.9219, 0.9715, 0.9566, 0.7073],
        [0.1494, 0.6039, 0.7336, 0.4211]])


In [9]:
#normal distribution
c  = torch.randn(3, 4)
print(c)

tensor([[-2.4079e-03,  1.3922e+00,  6.3192e-01,  7.4950e-01],
        [ 9.1934e-01,  1.7385e+00,  2.4524e+00,  5.4761e-01],
        [-1.0267e-01,  1.0441e+00, -5.7675e-01,  9.4711e-01]])


In [11]:
#random integers generator within range and dimensions
d  = torch.randint(3, 10, size=(4, 4))

print(d)

tensor([[8, 3, 8, 9],
        [4, 5, 9, 4],
        [9, 9, 6, 5],
        [7, 7, 3, 3]])


In [13]:
#setting the upper bound only for integer generator
e = torch.randint(10, size=(4,4))

print(e)

tensor([[1, 0, 8, 2],
        [2, 2, 0, 2],
        [2, 9, 9, 3],
        [1, 8, 1, 8]])


In [14]:
f = torch.zeros(2,3,4)

In [15]:
f

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
#same value tensors
g = torch.full((2,3,4), 5)

g

tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])

In [19]:
h = torch.ones(2,3,4)

h

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [21]:
i = torch.eye(4)

i

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [23]:
j = torch.diag(e)

j

tensor([1, 2, 9, 8])

In [24]:
e

tensor([[1, 0, 8, 2],
        [2, 2, 0, 2],
        [2, 9, 9, 3],
        [1, 8, 1, 8]])

In [25]:
e.shape

torch.Size([4, 4])

In [26]:
e.size()

torch.Size([4, 4])

In [27]:
e.ndim

2

In [30]:
len(e)

4