In [1]:
import torch

In [2]:
a  = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.int32)

In [3]:
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [4]:
#ten evenly distributed values between 1 and -1
b = torch.linspace(-1, 1, 10)

In [5]:
print(b)

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])


In [6]:
#random number generator
c = torch.rand(3, 4)

In [7]:
print(c)

tensor([[0.2521, 0.5153, 0.9227, 0.2004],
        [0.4450, 0.8499, 0.9100, 0.9325],
        [0.4122, 0.4410, 0.8380, 0.1649]])


In [8]:
#normal distribution
c  = torch.randn(3, 4)
print(c)

tensor([[ 1.5516,  0.2968, -0.2504,  0.8325],
        [ 0.6332,  1.1294,  0.0073, -0.1100],
        [ 1.0460, -0.2264, -0.6363, -1.0746]])


In [9]:
#random integers generator within range and dimensions
d  = torch.randint(3, 10, size=(4, 4))

print(d)

tensor([[8, 9, 9, 6],
        [6, 4, 5, 7],
        [3, 4, 9, 5],
        [9, 6, 5, 3]])


In [10]:
#setting the upper bound only for integer generator
e = torch.randint(10, size=(4,4))

print(e)

tensor([[6, 4, 1, 6],
        [9, 6, 5, 3],
        [3, 2, 8, 3],
        [9, 0, 3, 5]])


In [11]:
f = torch.zeros(2,3,4)

In [12]:
f

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
#same value tensors
g = torch.full((2,3,4), 5)

g

tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])

In [14]:
h = torch.ones(2,3,4)

h

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
i = torch.eye(4)

i

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [16]:
j = torch.diag(e)

j

tensor([6, 6, 8, 5])

In [17]:
e

tensor([[6, 4, 1, 6],
        [9, 6, 5, 3],
        [3, 2, 8, 3],
        [9, 0, 3, 5]])

In [18]:
e.shape

torch.Size([4, 4])

In [19]:
e.size()

torch.Size([4, 4])

In [20]:
e.ndim

2

In [21]:
len(e)

4

In [22]:
e.dtype

torch.int64

In [23]:
j = e.type(torch.float64)

j.dtype

torch.float64

In [24]:
k = torch.randn(3,4,5)

k

tensor([[[-0.3508,  0.0827,  0.2053, -1.1591,  0.0518],
         [-0.4701,  0.0057,  0.5433, -1.1736, -0.3837],
         [ 1.5479,  2.4236,  0.2433, -1.8217, -0.3956],
         [ 0.2593,  0.1377, -0.0543, -2.2811,  0.3066]],

        [[-1.4489,  0.7073,  0.8868,  1.4575, -1.4494],
         [-0.4884, -1.3832, -0.8376, -0.5320, -1.2606],
         [-0.6051,  3.0393, -0.5477,  0.8935,  1.7834],
         [-1.9805,  0.1053,  0.0537,  0.4205,  0.7123]],

        [[ 0.4460, -0.3049,  0.2118,  1.3635, -0.0485],
         [ 0.9861, -1.6776, -1.0222,  0.0347, -0.0239],
         [-0.3486,  0.8184, -0.8377, -1.6845,  0.0869],
         [ 0.0291, -0.9610, -0.5746, -0.4323,  0.2548]]])

In [25]:
print(k[1])

tensor([[-1.4489,  0.7073,  0.8868,  1.4575, -1.4494],
        [-0.4884, -1.3832, -0.8376, -0.5320, -1.2606],
        [-0.6051,  3.0393, -0.5477,  0.8935,  1.7834],
        [-1.9805,  0.1053,  0.0537,  0.4205,  0.7123]])


In [26]:
l = (k[2])
l

tensor([[ 0.4460, -0.3049,  0.2118,  1.3635, -0.0485],
        [ 0.9861, -1.6776, -1.0222,  0.0347, -0.0239],
        [-0.3486,  0.8184, -0.8377, -1.6845,  0.0869],
        [ 0.0291, -0.9610, -0.5746, -0.4323,  0.2548]])

In [27]:
print(k[1:, 2:4])

tensor([[[-0.6051,  3.0393, -0.5477,  0.8935,  1.7834],
         [-1.9805,  0.1053,  0.0537,  0.4205,  0.7123]],

        [[-0.3486,  0.8184, -0.8377, -1.6845,  0.0869],
         [ 0.0291, -0.9610, -0.5746, -0.4323,  0.2548]]])


In [28]:
print(k[:, None, :, None].shape)

torch.Size([3, 1, 4, 1, 5])


In [29]:
m = torch.unsqueeze(k, dim=3)

print(k.shape)
print(m.shape)

torch.Size([3, 4, 5])
torch.Size([3, 4, 5, 1])


In [30]:
n = torch.randn(3,4)

print(n)

tensor([[-0.0548, -0.4899, -0.1264, -1.0077],
        [ 0.8891, -1.2443,  0.1830,  0.5362],
        [ 1.2248, -0.9656, -0.0473, -1.0177]])


In [31]:
print(n[:, (n > -1).all(axis=0)])

tensor([[-0.0548, -0.1264],
        [ 0.8891,  0.1830],
        [ 1.2248, -0.0473]])


In [32]:
n

tensor([[-0.0548, -0.4899, -0.1264, -1.0077],
        [ 0.8891, -1.2443,  0.1830,  0.5362],
        [ 1.2248, -0.9656, -0.0473, -1.0177]])

In [34]:
m = torch.unsqueeze(n, dim=2)

print(n.shape)
print(m.shape)

torch.Size([3, 4])
torch.Size([3, 4, 1])


In [37]:
p = torch.randn(4,5)

print(p)
print(p[:, (p > -1).all(axis=0)])

tensor([[ 0.3341, -1.0784, -0.0481, -0.2946, -1.5876],
        [ 1.1691, -0.5613,  2.1671, -1.1272, -0.9665],
        [-1.0297,  0.1757, -0.6859,  1.5059,  0.2509],
        [-1.9490,  0.0161, -0.3797,  1.1315,  1.7057]])
tensor([[-0.0481],
        [ 2.1671],
        [-0.6859],
        [-0.3797]])


In [38]:
#concerting a 2d tensor to1d
r = torch.randn(4,5)

print(r)
print(r.ravel())

tensor([[ 1.0064,  0.9194, -0.9043,  0.7594, -0.2050],
        [-0.4598,  0.6706,  0.3470,  1.7483, -3.2241],
        [-1.5873,  1.4041, -0.9714,  0.8032, -0.2419],
        [ 1.8750, -0.2841,  2.0248, -2.1486, -0.5423]])
tensor([ 1.0064,  0.9194, -0.9043,  0.7594, -0.2050, -0.4598,  0.6706,  0.3470,
         1.7483, -3.2241, -1.5873,  1.4041, -0.9714,  0.8032, -0.2419,  1.8750,
        -0.2841,  2.0248, -2.1486, -0.5423])


In [39]:
print(r.reshape(-1))

tensor([ 1.0064,  0.9194, -0.9043,  0.7594, -0.2050, -0.4598,  0.6706,  0.3470,
         1.7483, -3.2241, -1.5873,  1.4041, -0.9714,  0.8032, -0.2419,  1.8750,
        -0.2841,  2.0248, -2.1486, -0.5423])
