In [1]:
import numpy as np
import pandas as pd 

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('/kaggle/input/clean-data-australia-rainfall/rainfall_data_australia.csv', index_col=None)

In [3]:
df.shape

(351587, 18)

In [4]:
df.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0     17.9     35.2       0.0         12.0      12.3             48   
1     17.9     35.2       0.0         12.0      12.3             48   
2     17.9     35.2       0.0         12.0      12.3             48   
3     17.9     35.2       0.0         12.0      12.3             48   
4     17.9     35.2       0.0         12.0      12.3             48   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0           6.0          20.0           20         13.0       1006.3   
1           6.0          20.0           20         13.0       1006.3   
2           6.0          20.0           20         13.0       1006.3   
3           6.0          20.0           20         13.0       1006.3   
4           6.0          20.0           20         13.0       1006.3   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  
0       1004.4         2         5     26.6     33.4          2             2  
1       1004.4         2         5     26.6     33.4          2             2  
2       1004.4         2         5     26.6     33.4          2             2  
3       1004.4         2         5     26.6     33.4          2             2  
4       1004.4         2         5     26.6     33.4          2             2

In [5]:
df.isna().any()

MinTemp           True
MaxTemp           True
Rainfall         False
Evaporation       True
Sunshine         False
WindGustSpeed    False
WindSpeed9am      True
WindSpeed3pm      True
Humidity9am      False
Humidity3pm       True
Pressure9am       True
Pressure3pm       True
Cloud9am         False
Cloud3pm         False
Temp9am          False
Temp3pm           True
RainToday        False
RainTomorrow     False
dtype: bool

In [6]:
df = df.dropna()

In [7]:
df.isna().any()

MinTemp          False
MaxTemp          False
Rainfall         False
Evaporation      False
Sunshine         False
WindGustSpeed    False
WindSpeed9am     False
WindSpeed3pm     False
Humidity9am      False
Humidity3pm      False
Pressure9am      False
Pressure3pm      False
Cloud9am         False
Cloud3pm         False
Temp9am          False
Temp3pm          False
RainToday        False
RainTomorrow     False
dtype: bool

In [8]:
df.shape

(349416, 18)

In [9]:
df.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [10]:
df['RainTomorrow'].unique()

array([2, 1, 3])

In [11]:
x_cols = ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday']

In [12]:
x = df[x_cols]

y = df['RainTomorrow']

In [13]:
x

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0          17.9     35.2       0.0         12.0      12.3             48   
1          17.9     35.2       0.0         12.0      12.3             48   
2          17.9     35.2       0.0         12.0      12.3             48   
3          17.9     35.2       0.0         12.0      12.3             48   
4          17.9     35.2       0.0         12.0      12.3             48   
...         ...      ...       ...          ...       ...            ...   
351582     20.2     31.7       0.0          5.6      10.7             30   
351583     20.2     31.7       0.0          5.6      10.7             30   
351584     20.2     31.7       0.0          5.6      10.7             30   
351585     20.2     31.7       0.0          5.6      10.7             30   
351586     20.2     31.7       0.0          5.6      10.7             30   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0                6.0          20.0           20         13.0       1006.3   
1                6.0          20.0           20         13.0       1006.3   
2                6.0          20.0           20         13.0       1006.3   
3                6.0          20.0           20         13.0       1006.3   
4                6.0          20.0           20         13.0       1006.3   
...              ...           ...          ...          ...          ...   
351582          15.0           7.0           73         32.0       1013.9   
351583          15.0           7.0           73         32.0       1013.9   
351584          15.0           7.0           73         32.0       1013.9   
351585          15.0           7.0           73         32.0       1013.9   
351586          15.0           7.0           73         32.0       1013.9   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  
0            1004.4         2         5     26.6     33.4          2  
1            1004.4         2         5     26.6     33.4          2  
2            1004.4         2         5     26.6     33.4          2  
3            1004.4         2         5     26.6     33.4          2  
4            1004.4         2         5     26.6     33.4          2  
...             ...       ...       ...      ...      ...        ...  
351582       1009.7         6         5     25.4     31.0          2  
351583       1009.7         6         5     25.4     31.0          2  
351584       1009.7         6         5     25.4     31.0          2  
351585       1009.7         6         5     25.4     31.0          2  
351586       1009.7         6         5     25.4     31.0          2  

[349416 rows x 17 columns]

In [14]:
y.unique()

array([2, 1, 3])

In [15]:
y = pd.DataFrame(y)

In [16]:
scaler = MinMaxScaler().fit(x)

x = scaler.transform(x)

In [17]:
x

array([[0.64566929, 0.70681818, 0.        , ..., 0.68238213, 0.7004717 ,
        1.        ],
       [0.64566929, 0.70681818, 0.        , ..., 0.68238213, 0.7004717 ,
        1.        ],
       [0.64566929, 0.70681818, 0.        , ..., 0.68238213, 0.7004717 ,
        1.        ],
       ...,
       [0.70603675, 0.62727273, 0.        , ..., 0.65260546, 0.64386792,
        1.        ],
       [0.70603675, 0.62727273, 0.        , ..., 0.65260546, 0.64386792,
        1.        ],
       [0.70603675, 0.62727273, 0.        , ..., 0.65260546, 0.64386792,
        1.        ]])

In [18]:
encoder = OneHotEncoder(handle_unknown='ignore').fit(y)

y = encoder.transform(y)

In [19]:
y

<349416x3 sparse matrix of type '<class 'numpy.float64'>'
	with 349416 stored elements in Compressed Sparse Row format>