<a href="https://colab.research.google.com/github/wessware/pytorch-101/blob/main/pytorch_differentiation_and_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch

import numpy as np

In [38]:
a = torch.tensor([1,2,3])

In [39]:
a

tensor([1, 2, 3])

In [40]:
a.shape

torch.Size([3])

In [41]:
a.dtype

torch.int64

In [42]:
b = torch.tensor([2., 3. ,4.], requires_grad=True)

In [43]:
c = torch.tensor([3.6], requires_grad=True)

d = c * c
d.backward()

In [44]:
print(c.grad)

tensor([7.2000])


AutoGrad for Polynomial Regression

In [45]:
pol = np.poly1d([2, 3, 5])

In [46]:
print(pol)

   2
2 x + 3 x + 5


In [47]:
pol(2.8)

29.08

In [48]:
d = 36

x = np.random.randn(d, 1) * 5
y = pol(x)

In [49]:
x

array([[  0.69405438],
       [ -4.85238163],
       [-13.27959818],
       [  2.34649487],
       [  5.34791484],
       [  1.1884433 ],
       [ -0.77651399],
       [  4.81236963],
       [ -1.6366191 ],
       [  8.88534572],
       [ -9.9229198 ],
       [  7.7021306 ],
       [  0.64969721],
       [  4.12023623],
       [  1.03687016],
       [-10.51504392],
       [  6.98438264],
       [ -8.20981994],
       [  6.85921254],
       [  9.62890783],
       [  2.25393776],
       [  2.36576114],
       [  0.59242414],
       [  7.63575858],
       [ -1.53798361],
       [  0.17533921],
       [ -4.63514482],
       [ 12.45653065],
       [  1.44948598],
       [ -2.81635235],
       [  4.1784001 ],
       [ -7.09454634],
       [ -2.92685328],
       [ -3.74866606],
       [ -1.80794608],
       [  2.10457159]])

In [50]:
y

array([[  8.04558612],
       [ 37.53407013],
       [317.85666107],
       [ 23.05156096],
       [ 78.24413073],
       [ 11.39012487],
       [  3.87640598],
       [ 65.75491174],
       [  5.44718686],
       [189.55477419],
       [172.15991519],
       [146.7520235 ],
       [  7.79330457],
       [ 51.31340188],
       [ 10.26080992],
       [194.5871655 ],
       [123.51634974],
       [115.17282698],
       [119.67523089],
       [219.31845539],
       [ 21.92228413],
       [ 23.29093502],
       [  7.47920512],
       [144.51689379],
       [  5.11683635],
       [  5.58750532],
       [ 34.06370048],
       [352.69990347],
       [ 13.55047719],
       [ 12.41462406],
       [ 52.45325516],
       [ 84.38153647],
       [ 13.3523804 ],
       [ 21.85899631],
       [  6.1134998 ],
       [ 20.17215792]])

Evaluating the coefficients of a polynomial

In [51]:
poly_1 = np.poly1d([6,7,8])

j = 32

In [52]:
x_ = np.random.randn(j, 1) * 8
y_ = poly_1(x_)

In [53]:
X = np.hstack([x_*x_, np.ones_like(x_)])

In [54]:
r = torch.randn(3, 1, requires_grad=True)
k = torch.tensor(X, dtype = torch.float32)
l = torch.tensor(y_, dtype=torch.float32)

In [55]:
optimizer = torch.optim.NAdam([r], lr=0.01)

print(r)

tensor([[ 0.9667],
        [-1.6016],
        [ 1.3918]], requires_grad=True)


In [56]:
for _ in range(1000):
  optimizer.zero_grad()

  y_pred = k @ r

  mse = torch.mean(torch.square(y_ - y_pred))
  mse.backward()
  optimizer.step()


RuntimeError: ignored

In [ ]:


# Run optimizer
for _ in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print(w)