<a href="https://colab.research.google.com/github/wessware/pytorch-101/blob/main/pytorch_differentiation_and_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch

import numpy as np

In [3]:
a = torch.tensor([1,2,3])

In [4]:
a

tensor([1, 2, 3])

In [5]:
a.shape

torch.Size([3])

In [6]:
a.dtype

torch.int64

In [8]:
b = torch.tensor([2., 3. ,4.], requires_grad=True)

In [9]:
c = torch.tensor([3.6], requires_grad=True)

d = c * c
d.backward()

In [11]:
print(c.grad)

tensor([7.2000])


AutoGrad for Polynomial Regression

In [15]:
pol = np.poly1d([2, 3, 5])

In [16]:
print(pol)

   2
2 x + 3 x + 5


In [19]:
pol(2.8)

29.08

In [20]:
d = 36

x = np.random.randn(d, 1) * 5
y = pol(x)

In [22]:
x

array([[-0.24880783],
       [-4.52569126],
       [-3.14057011],
       [-4.8164715 ],
       [ 3.01710122],
       [ 0.08493543],
       [-7.02565989],
       [ 3.38133267],
       [-7.64599017],
       [-4.51613751],
       [-6.55514302],
       [-5.32429782],
       [ 0.9707846 ],
       [-7.74607773],
       [-5.34329434],
       [-5.06940439],
       [-9.17927177],
       [ 0.82360029],
       [ 5.0420113 ],
       [-5.13403266],
       [-0.70543574],
       [-5.42994978],
       [ 3.19053193],
       [ 2.58630391],
       [ 0.48314687],
       [-6.58715831],
       [-7.06085353],
       [-0.64476573],
       [ 1.8751103 ],
       [-1.41114569],
       [-5.41368285],
       [-0.35833368],
       [ 7.32461216],
       [ 2.45746948],
       [ 7.64865741],
       [-7.72563917]])

In [23]:
y

array([[  4.37738719],
       [ 32.38668901],
       [ 15.30465095],
       [ 36.94738092],
       [ 32.25710326],
       [  5.26923434],
       [ 82.64281413],
       [ 38.01081922],
       [ 98.9843609 ],
       [ 32.24258354],
       [ 71.27437085],
       [ 45.72340116],
       [  9.79719927],
       [101.76520726],
       [ 46.07170573],
       [ 41.18950851],
       [145.98024527],
       [  8.82743576],
       [ 70.96978969],
       [ 42.31448481],
       [  3.87897195],
       [ 47.67885979],
       [ 34.93058374],
       [ 26.13684751],
       [  6.91630241],
       [ 72.0198342 ],
       [ 83.52874465],
       [  3.8971485 ],
       [ 17.6574082 ],
       [  4.74922725],
       [ 47.37487544],
       [  4.18180502],
       [134.27372316],
       [ 24.45072088],
       [144.94989248],
       [101.19408375]])