<a href="https://colab.research.google.com/github/wessware/pytorch-101/blob/main/pytorch_differentiation_and_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import torch

import numpy as np

In [42]:
a = torch.tensor([1,2,3])

In [43]:
a

tensor([1, 2, 3])

In [44]:
a.shape

torch.Size([3])

In [45]:
a.dtype

torch.int64

In [46]:
b = torch.tensor([2., 3. ,4.], requires_grad=True)

In [47]:
c = torch.tensor([3.6], requires_grad=True)

d = c * c
d.backward()

In [48]:
print(c.grad)

tensor([7.2000])


AutoGrad for Polynomial Regression

In [49]:
pol = np.poly1d([2, 3, 5])

In [50]:
print(pol)

   2
2 x + 3 x + 5


In [51]:
pol(2.8)

29.08

In [52]:
d = 36

x = np.random.randn(d, 1) * 5
y = pol(x)

In [53]:
x

array([[-5.47980184],
       [-2.77009953],
       [ 1.02029747],
       [ 3.23120462],
       [-3.10959608],
       [ 4.46696814],
       [-4.98560381],
       [12.10378397],
       [ 4.88919846],
       [ 0.46636447],
       [ 0.37383612],
       [ 1.90284214],
       [ 6.07830115],
       [ 3.09643675],
       [11.20466265],
       [12.24782022],
       [ 8.05159866],
       [-4.08855519],
       [ 5.88535802],
       [11.31090547],
       [ 7.25912858],
       [-0.57275308],
       [ 0.41729122],
       [-2.45026182],
       [ 5.71617127],
       [ 3.37360774],
       [-2.87017686],
       [ 5.52765633],
       [ 0.75498716],
       [ 2.19751736],
       [ 0.06268353],
       [ 6.39163944],
       [ 0.8330524 ],
       [ 4.85265571],
       [ 5.7158967 ],
       [-0.39877454]])

In [54]:
y

array([[ 48.61705093],
       [ 12.03660423],
       [ 10.14290623],
       [ 35.57498049],
       [ 15.01038731],
       [ 58.30851319],
       [ 39.75567924],
       [334.31452463],
       [ 67.47611854],
       [  6.83408503],
       [  6.40101525],
       [ 17.95014285],
       [ 97.12639321],
       [ 33.4651514 ],
       [289.7029181 ],
       [341.76166101],
       [158.81127778],
       [ 26.16690152],
       [ 91.9309522 ],
       [294.80588138],
       [132.16728132],
       [  3.93783294],
       [  6.6001376 ],
       [  9.65678052],
       [ 87.49774169],
       [ 37.88328151],
       [ 12.86529981],
       [ 82.69293807],
       [  8.40497273],
       [ 21.25071715],
       [  5.19590903],
       [105.88102788],
       [  8.88710981],
       [ 66.6545019 ],
       [ 87.49064038],
       [  4.12171864]])

Evaluating the coefficients of a polynomial

In [71]:
poly_1 = np.poly1d([4,5,6])

j = 32

In [72]:
x_ = np.random.randn(j, 1) * 8
y_ = poly_1(x_)

In [73]:
X = np.hstack([x_*x_, x_, np.ones_like(x_)])

In [74]:
r = torch.randn(3, 1, requires_grad=True)
k = torch.tensor(X, dtype = torch.float32)
l = torch.tensor(y_, dtype=torch.float32)

In [75]:
optimizer = torch.optim.NAdam([r], lr=0.01)

print(r)

tensor([[-1.2253],
        [-0.8011],
        [-0.1949]], requires_grad=True)


In [76]:
for _ in range(1000):
  optimizer.zero_grad()

  y_pred = k @ r

  mse = torch.mean(torch.square(l - y_pred))
  mse.backward()
  optimizer.step()


In [77]:
print(r)

tensor([[3.7063],
        [1.3463],
        [4.6920]], requires_grad=True)
